# Movie Recomendation  System Using Singular Value System 

* imorting Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

* load Dataset

In [8]:
ratingdata=pd.io.parsers.read_csv(r'C:\Users\Lenovo\Desktop\Data Science\Machine Learning\22_MovieRecommendationSystemUsingSVD\ratings.dat',names=['user_id','movie_id','rating','time'],
                             engine='python',delimiter='::')
moviedata=pd.io.parsers.read_csv(r'C:\Users\Lenovo\Desktop\Data Science\Machine Learning\22_MovieRecommendationSystemUsingSVD\movies.dat',names=['movie_id','title','genre'],
                            engine='python',delimiter='::')



In [9]:
print(ratingdata)

         user_id  movie_id  rating       time
0              1      1193       5  978300760
1              1       661       3  978302109
2              1       914       3  978301968
3              1      3408       4  978300275
4              1      2355       5  978824291
...          ...       ...     ...        ...
1000204     6040      1091       1  956716541
1000205     6040      1094       5  956704887
1000206     6040       562       5  956704746
1000207     6040      1096       4  956715648
1000208     6040      1097       4  956715569

[1000209 rows x 4 columns]


In [10]:
print(moviedata)

      movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                             genre  
0      Animation|Children's|Comedy  
1     Adventure|Children's|Fantasy  
2                   Comedy|Romance  
3                     Comedy|Drama  
4                           Comedy  
...                            ...  
3878                        Comedy  
3879                         Drama  
3880              

* Creating  the rating Matrix

In [12]:
ratingMatrix=np.ndarray(shape=(np.max(rating.movie_id.values),np.max(rating.user_id.values)),
                     dtype=np.uint8)
ratingMatrix[rating.movie_id.values-1,rating.user_id.values-1]=ratingdata.rating.values
print(ratingMatrix)

[[5 0 0 ... 0 0 3]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


* Subtract Mean off - Normalization

In [13]:
normalizedMatrix=ratingMatrix-np.asarray([(np.mean(ratingMatrix,1))]).T
print(normalizedMatrix)

[[ 3.57400662 -1.42599338 -1.42599338 ... -1.42599338 -1.42599338
   1.57400662]
 [-0.37152318 -0.37152318 -0.37152318 ... -0.37152318 -0.37152318
  -0.37152318]
 [-0.23874172 -0.23874172 -0.23874172 ... -0.23874172 -0.23874172
  -0.23874172]
 ...
 [-0.03278146 -0.03278146 -0.03278146 ... -0.03278146 -0.03278146
  -0.03278146]
 [-0.02582781 -0.02582781 -0.02582781 ... -0.02582781 -0.02582781
  -0.02582781]
 [-0.24288079 -0.24288079 -0.24288079 ... -0.24288079 -0.24288079
  -0.24288079]]


* Compute SVD

In [14]:
A=normalizedMatrix.T/np.sqrt(ratingMatrix.shape[0]-1)
U,S,V=np.linalg.svd(A)

* Calculate cosine similarity , sort by most similar and return the top N

In [15]:
def similar(ratingdata,moviedata,top_n=10):
    index=movie_id-1     # mivie id start from 1
    
    movie_row=ratingdata[index,:]
    magnitude=np.sqrt(np.einsum('ij,ij->i',ratingdata,ratingdata))
    
    similarity = np.dot(movie_row,ratingdata.T)/(magnitude[index]*magnitude)
    sort_indexes=np.argsort(-similarity)
    return sort_indexes[:top_n]

* Select k principle component to represent the movies , a movie_id to find  recommendations and print the top_n result

In [21]:
k=60
movie_id=20
top_in=7
sliced=V.T[:,:k]
indexes=similar(sliced,movie_id,top_in)

print('Recommendation for movie {0}:\n'.format(moviedata[moviedata.movie_id==movie_id].title.values[0]))
for id in indexes +1:
    print(moviedata[moviedata.movie_id==id].title.values[0])
    
    

Recommendation for movie Money Train (1995):

Money Train (1995)
Substitute, The (1996)
Sudden Death (1995)
Drop Zone (1994)
Metro (1997)
Specialist, The (1994)
Fled (1996)


C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys
